"""add sub_types

Revision ID: 34b3a6c80fc7
Revises: 1a9618cf4620
Create Date: 2025-06-23 17:39:48.953052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '34b3a6c80fc7'
down_revision: Union[str, Sequence[str], None] = '1a9618cf4620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sub_types',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('image', sa.String(), nullable=False),
        sa.Column('sequence', sa.Integer(), nullable=False),
        sa.Column('type_id', sa.UUID(), nullable=False),
        sa.CheckConstraint('sequence > 0', name='sequence_positive'),
        sa.ForeignKeyConstraint(['type_id'], ['types.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('image')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_types')
    # ### end Alembic commands ###
