"""add documents

Revision ID: bda5778a11dd
Revises: 1dbf7453dd9c
Create Date: 2025-06-23 17:24:03.786943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'bda5778a11dd'
down_revision: Union[str, Sequence[str], None] = '1dbf7453dd9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'documents',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('media', sa.String(), nullable=True),
        sa.Column('sequence', sa.Integer(), nullable=False),
        sa.CheckConstraint('sequence > 0', name='sequence_positive'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('media')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###
