"""edit documents

Revision ID: 8fcad086d66a
Revises: 34b3a6c80fc7
Create Date: 2025-06-23 17:42:24.298030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fcad086d66a'
down_revision: Union[str, Sequence[str], None] = '34b3a6c80fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('sub_type_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'documents', 'sub_types', ['sub_type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'sub_type_id')
    # ### end Alembic commands ###
